### ISSUE TITLE
Error with hexadecimal

### ISSUE THREAD

**Issue by soaresdiogo** [hylander0/Iteedee.ApkReader#16]
The '.' character, hexadecimal value 0x00, cannot be included in a name. Line 1, position 6.

**Comment by soaresdiogo** [comment]
It not working with AndroidManifest.xml built by AndroidStudio 3

**Comment by DevilGeek** [comment]
This fork is working : https://github.com/vassav/Iteedee.ApkReader

**Comment by hylander0** [comment]
@vassav Please create a pull request and I will merge it in.

**Comment by vassav** [comment]
You closed it. See #13
