### ISSUE TITLE
some apks throw an exeption while reading resources

### ISSUE THREAD

**Issue by scrat911** [hylander0/Iteedee.ApkReader#4]
Hi!, i dont know if this issue have something to do with [this](https://github.com/hylander0/Iteedee.ApkReader/issues/1) Fix, but, i'm still getting this erros with some .apk files(like facebook app, SU, etc)  while reading their resources, its in the while loop fixed but, still getting an error:

could you please tell me if i did something wrong. thz

(Sorry for my english.)

> Message
> The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' >fallback 'System.Text.DecoderReplacementFallback'. Parameter name: chars
> ParamName
> chars
> StackTrace
> at Iteedee.ApkReader.ApkReader.extractInfo(XmlDocument manifestXml, Byte[] resources_arsx) in d:\Work\apk parser\Iteedee.ApkReader-master\Iteedee.ApkReader\ApkReader.cs:line 243 at Iteedee.ApkReader.ApkReader.extractInfo(Byte[] manifest_xml, Byte[] resources_arsx) in d:\Work\apk parser\Iteedee.ApkReader-master\Iteedee.ApkReader\ApkReader.cs:line 108 at Windows_Phone_App_Store.Models.ApkStoreDiscover.discover() in d:\Documentos\Visual Studio 2013\Projects\Windows Phone App Store\Windows Phone App Store\Models\apkParser.cs:line 132
> 
> HelpLink
> Source
> Iteedee.ApkReader
> HResult
> -2147024809

**Comment by hylander0** [comment]
@scrat911 @kkguo  has provided a fix that might address your problem as well.  Let me know if you have a chance to confirm this.  Thanks

**Comment by vassav** [comment]
Pull request #13 fix it issue
